name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'feat']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'deps']
  - title: '🧪 Tests'
    labels: ['test', 'tests']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No user-facing changes in this release.'
template: |
  ## What’s Changed
  $CHANGES

