name: ci

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  python-checks:
    name: Lint, type, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Ruff (lint)
        run: ruff check .

      - name: mypy (type check)
        run: mypy app

      - name: Pytest
        env:
          PYTHONWARNINGS: error
        run: pytest

  build-images:
    name: Build Docker images (no push)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile.api
          - name: frontend
            dockerfile: Dockerfile.web
          - name: all-in-one
            dockerfile: Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: false
          load: false
          provenance: false

