name: docker

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile.api
            name_suffix: '-api'
          - name: frontend
            dockerfile: Dockerfile.web
            name_suffix: '-web'
          - name: all-in-one
            dockerfile: Dockerfile
            name_suffix: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image variables
        id: vars
        shell: bash
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          echo "repo_lower=${repo,,}" >> "$GITHUB_OUTPUT"
          ns="${{ secrets.DOCKERHUB_NAMESPACE }}"
          if [ -z "$ns" ]; then ns="${{ secrets.DOCKERHUB_USERNAME }}"; fi
          echo "namespace_lower=${ns,,}" >> "$GITHUB_OUTPUT"

      - name: Build ${{ matrix.name }} (PR; no push)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: false
          platforms: linux/amd64
          tags: ${{ steps.vars.outputs.repo_lower }}${{ matrix.name_suffix }}:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }} (main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            docker.io/${{ steps.vars.outputs.namespace_lower }}/${{ steps.vars.outputs.repo_lower }}${{ matrix.name_suffix }}:latest
            docker.io/${{ steps.vars.outputs.namespace_lower }}/${{ steps.vars.outputs.repo_lower }}${{ matrix.name_suffix }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
