name: docker

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile.api
            suffix: api
          - name: frontend
            dockerfile: Dockerfile.web
            suffix: web
    env:
      REPO_LOWER: ${{ toLower(github.event.repository.name) }}
      NAMESPACE_LOWER: ${{ toLower(secrets.DOCKERHUB_NAMESPACE || secrets.DOCKERHUB_USERNAME) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.name }} (PR; no push)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: false
          platforms: linux/amd64
          tags: ${{ env.REPO_LOWER }}-${{ matrix.suffix }}:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }} (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            docker.io/${{ env.NAMESPACE_LOWER }}/${{ env.REPO_LOWER }}-${{ matrix.suffix }}:latest
            docker.io/${{ env.NAMESPACE_LOWER }}/${{ env.REPO_LOWER }}-${{ matrix.suffix }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
