name: release

on:
  push:
    tags:
      - '*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile.api
            suffix: api
          - name: frontend
            dockerfile: Dockerfile.web
            suffix: web
    env:
      REPO_LOWER: ${{ toLower(github.event.repository.name) }}
      TAG_LOWER: ${{ toLower(github.ref_name) }}
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64
          tags: |
            docker.io/${{ env.USERNAME }}/${{ env.REPO_LOWER }}-${{ matrix.suffix }}:${{ env.TAG_LOWER }}
            docker.io/${{ env.USERNAME }}/${{ env.REPO_LOWER }}-${{ matrix.suffix }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

