name: release-drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_release_draft:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
