name: release-drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled, closed]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

