name: release

on:
  push:
    tags:
      - '*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile.api
            name_suffix: '-api'
          - name: frontend
            dockerfile: Dockerfile.web
            name_suffix: '-web'
          - name: all-in-one
            dockerfile: Dockerfile
            name_suffix: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image variables
        id: vars
        shell: bash
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          echo "repo_lower=${repo,,}" >> "$GITHUB_OUTPUT"
          ns="${{ secrets.DOCKERHUB_NAMESPACE }}"
          if [ -z "$ns" ]; then ns="${{ secrets.DOCKERHUB_USERNAME }}"; fi
          echo "namespace_lower=${ns,,}" >> "$GITHUB_OUTPUT"
          echo "tag_lower=${GITHUB_REF_NAME,,}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            docker.io/${{ steps.vars.outputs.namespace_lower }}/${{ steps.vars.outputs.repo_lower }}${{ matrix.name_suffix }}:${{ steps.vars.outputs.tag_lower }}
            docker.io/${{ steps.vars.outputs.namespace_lower }}/${{ steps.vars.outputs.repo_lower }}${{ matrix.name_suffix }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
