name: sbom

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-and-attach-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SBOM (SPDX JSON) for repo
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom-${{ github.event.release.tag_name }}.spdx.json

      - name: Upload SBOM to release
        uses: softprops/action-gh-release@v1
        with:
          files: sbom-${{ github.event.release.tag_name }}.spdx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

